package view;

import controller.ReportesController;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.generador.GeneradorSQL;
import model.vo.*;

/**
 *
 * @author julie
 */
public class InformesGUI extends javax.swing.JFrame {

    DefaultTableModel te;

    /**
     * Creates new form InformesGUI
     */
    public InformesGUI() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Informes Proyectos de Construccion Ministerio de Vivienda");

    }

    public InformesGUI(GeneradorSQL sql) {
        this();
        mostrarInformeGenerado(sql);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformes = new javax.swing.JTable();
        lblTituloInforme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuInf1r5 = new javax.swing.JMenuItem();
        menuInf2r5 = new javax.swing.JMenuItem();
        menuInf3r5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuComprasDeLider = new javax.swing.JMenuItem();
        menuDeudasPorProyecto = new javax.swing.JMenuItem();
        menuProyectoBanco = new javax.swing.JMenuItem();
        menuGeneradorInformes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo1n.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("INFORMES PROYECTOS DE CONSTRUCCIÓN");

        tblInformes.setBackground(new java.awt.Color(0, 0, 0));
        tblInformes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tblInformes.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tblInformes.setForeground(new java.awt.Color(255, 255, 255));
        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Informe"
            }
        ));
        tblInformes.setToolTipText("Haga clic en el titulo de la columna para ordenar los datos");
        tblInformes.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblInformes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblInformes.setShowGrid(true);
        tblInformes.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tblInformes);

        lblTituloInforme.setBackground(new java.awt.Color(0, 0, 0));
        lblTituloInforme.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblTituloInforme.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloInforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInforme.setText("Informes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        jMenu3.setText("Informes Prediseñados");

        jMenu4.setText("Informes R5");

        menuInf1r5.setText("Primer Informe");
        menuInf1r5.setToolTipText("");
        menuInf1r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInf1r5ActionPerformed(evt);
            }
        });
        jMenu4.add(menuInf1r5);

        menuInf2r5.setText("Segundo Informe");
        menuInf2r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInf2r5ActionPerformed(evt);
            }
        });
        jMenu4.add(menuInf2r5);

        menuInf3r5.setText("Tercer Informe");
        menuInf3r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInf3r5ActionPerformed(evt);
            }
        });
        jMenu4.add(menuInf3r5);

        jMenu3.add(jMenu4);

        jMenu5.setText("Informes R4");

        menuComprasDeLider.setText("Compras de Lider");
        menuComprasDeLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprasDeLiderActionPerformed(evt);
            }
        });
        jMenu5.add(menuComprasDeLider);

        menuDeudasPorProyecto.setText("Deudas por Proyecto");
        menuDeudasPorProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeudasPorProyectoActionPerformed(evt);
            }
        });
        jMenu5.add(menuDeudasPorProyecto);

        menuProyectoBanco.setText("Proyecto Financiado Banco");
        menuProyectoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProyectoBancoActionPerformed(evt);
            }
        });
        jMenu5.add(menuProyectoBanco);

        jMenu3.add(jMenu5);

        jMenu2.add(jMenu3);

        menuGeneradorInformes.setText("Generador de Informes");
        menuGeneradorInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeneradorInformesActionPerformed(evt);
            }
        });
        jMenu2.add(menuGeneradorInformes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuComprasDeLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprasDeLiderActionPerformed
        ReportesController reporte = new ReportesController();
        ComprasDeLiderVo datosTabla = reporte.ComprasDeLider();

//        te = (DefaultTableModel)tblInformes.getModel();
//        te = new DefaultTableModel(null, datosTabla.getNombreColumnas().toArray());
//        tblInformes.setModel(te);
        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas().toArray()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);
        lblTituloInforme.setText("Compras de Lider");


    }//GEN-LAST:event_menuComprasDeLiderActionPerformed

    private void menuInf1r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInf1r5ActionPerformed
        ReportesController reporte = new ReportesController();
        PrimerInformeR5Vo datosTabla = reporte.PrimerInformeR5();

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Primer Informe - Listado de Lideres");

    }//GEN-LAST:event_menuInf1r5ActionPerformed

    private void menuInf2r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInf2r5ActionPerformed
        ReportesController reporte = new ReportesController();
        SegundoInformeR5Vo datosTabla = reporte.SegundoInformeR5();

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Segundo Informe - Proyectos Casa Campestre en la Costa");

    }//GEN-LAST:event_menuInf2r5ActionPerformed

    private void menuInf3r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInf3r5ActionPerformed

        ReportesController reporte = new ReportesController();
        TercerInformeR5Vo datosTabla = reporte.TercerInformeR5();

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Tercer Informe - Compras a Homecenter para Proyectos en Salento");

    }//GEN-LAST:event_menuInf3r5ActionPerformed

    private void menuDeudasPorProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeudasPorProyectoActionPerformed

        Double limiteInferior = Double.parseDouble(JOptionPane.showInputDialog("Digite el valor mínimo de deuda a consultar"));
        ReportesController reporte = new ReportesController(limiteInferior);
        DeudasPorProyectoVo datosTabla = reporte.DeudasPorProyecto();

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Deudas por Proyecto");

    }//GEN-LAST:event_menuDeudasPorProyectoActionPerformed

    private void menuProyectoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProyectoBancoActionPerformed

        String banco = JOptionPane.showInputDialog("Ingrese el banco a consultar");
        ReportesController reporte = new ReportesController(banco);
        ProyectoBancoVo datosTabla = reporte.ProyectoBanco();

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas()
        ) {
            Class[] types = datosTabla.getTipoColumnas();
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Proyectos Financiados por " + banco);


    }//GEN-LAST:event_menuProyectoBancoActionPerformed

    private void menuGeneradorInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeneradorInformesActionPerformed
        GeneradorInformesGUI gi = new GeneradorInformesGUI();
        this.dispose();
        gi.setVisible(true);

    }//GEN-LAST:event_menuGeneradorInformesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mostrarInformeGenerado(GeneradorSQL sql) {

        ReportesController reporte = new ReportesController();
        GeneradorInformeVo datosTabla = reporte.generarInforme(sql.generarSQL(), sql.getListaCampos(), sql.getTipoCampos());

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
                null,
                datosTabla.getNombreColumnas().toArray()
        ) {
            Class[] types = sql.getTipoCamposArray();
            boolean[] canEdit = sql.getCanEdit();

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        te = (DefaultTableModel) tblInformes.getModel();
        while (datosTabla.Next()) {
            te.addRow(datosTabla.obtenerRegistroActual().toArray());
        }
        tblInformes.setModel(te);

        //Configura tabla para ordenar por columna
        TableRowSorter<TableModel> ordenarColumna = new TableRowSorter<TableModel>(te);
        tblInformes.setRowSorter(ordenarColumna);
        tblInformes.setAutoCreateRowSorter(true);

        lblTituloInforme.setText("Informe Generado");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloInforme;
    private javax.swing.JMenuItem menuComprasDeLider;
    private javax.swing.JMenuItem menuDeudasPorProyecto;
    private javax.swing.JMenuItem menuGeneradorInformes;
    private javax.swing.JMenuItem menuInf1r5;
    private javax.swing.JMenuItem menuInf2r5;
    private javax.swing.JMenuItem menuInf3r5;
    private javax.swing.JMenuItem menuProyectoBanco;
    private javax.swing.JTable tblInformes;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/escudoColombia.png"));
        return retValue;
    }
}
